### ISSUE TITLE
Assets

### ISSUE THREAD

**Issue by Aeirex** [Pandacoder/blasters#1]
The assets are not in the Public Domain.

**Comment by hilts-vaughan** [comment]
Please provide a proper DCMA notice and declaration of copyright so it can be processed accordingly to the DCMA Policy of Github 

Thanks

**Comment by Aeirex** [comment]
@hilts-vaughan, the project was given to me and all assets included. The source-code is yours, but the actual assets were created by Rory, and I own those assets now.

**Comment by hilts-vaughan** [comment]
Hi Seth,

Since this is a professional setting, please leave personal matters aside and provide the appropriate DCMA notices.

Thanks.

**Comment by Pandacoder** [comment]
@Aeirex

There is nothing stating the repository or the contents (code _or_ art assets) are public domain.

This does not constitute a DMCA notice.

![screenshot_2016-11-16-14-04-52](https://cloud.githubusercontent.com/assets/1476550/20361732/b3895b9a-ac06-11e6-9eee-d56d1c06ea88.png)

**Comment by Aeirex** [comment]
@Pandacoder the DMCA is supposed to be done after the author of the repo refuses to do anything about it. I will take it further if you do not respect the fishes.

**Comment by hilts-vaughan** [comment]
A DCMA request is to prove you own the right over the assets. Please provide a full-listing of all files you own and the proof and we will happily comply in your request.

Unfortunately, if I compiled with every request I got on the Internet for takedowns, a lot of stuff would be gone! Proof is a necessity and exacts.

**Comment by Pandacoder** [comment]
@Aeirex I am not bound by a confidentiality agreement so posting the e-mail is a moot point. That being said, while I pushed the repository so that potential employers could see our work, @hilts-vaughan should most certainly be part of any e-mail conversation (private or otherwise) as this is just as much, if not more, his work.

As per what @hilts-vaughan said, you will need to provide proof of your allegations.

**Comment by Aeirex** [comment]
@Pandacoder It is a sign of respect. Vaughan has an email, you can send him it if you wish.

The PSDs were never meant to be released publicly, these files are meant to be private files. You do not own them, Justin does. Justin gave me Blasters and Silverdale. I have known about this for years, but I didn't bother to tell you to take them down until now.

I send him a message on Facebook about it.

**Comment by Pandacoder** [comment]
@Aeirex Again, you merely stating this does not constitute proof of your claims, and neither of us will take any further action. You also are providing no proof that you are legally permitted to issue a DMCA on Justin's behalf.

**Comment by hilts-vaughan** [comment]
@Aeirex I have no qualms taking down things owned by their respective owners. However, as noted by @Pandacoder you will need to provide proof of ownership.

Thanks for your cooperation.

**Comment by JustinSD** [comment]
Guys stop being dickheads... I handed over every single asset I've ever purchased for Blasters, SD Classic, any UI work for SD HD. Everything is currently owned by Seth and he has full rights to them. 

These projects have been bunked for almost 3 years now.. and the fact you guys are pulling this crap on Seth is pathetic.

**Comment by Aeirex** [comment]
I don't like failure, and I am trying to finish what was not finished due to programmers. I learned how to program because I got tired of people like Robbie being cocky arrogant assholes and being forced to work with them. So I quit, getting away from the toxic people always attacking me. You are too clueless to really understand when you are in the wrong. Although, I never quit when it comes to a project. I finish what I start.

**Comment by hilts-vaughan** [comment]
@JustinSD Hi, I am not sure who is being a "dickhead". You were created "Joined on Nov 17, 2016". I have no reason to believe you own or @Aeirex own the rights to these assets.

I have cooperated this entire time. Please serve proper notice and the asset(s) you wish removed, and I will remove them promptly.

If you want, I can link you to the part of the law which allows me to request this of you.

**Comment by DylanDodds** [comment]
@Aeirex We're sorry you seem to be having issues with this particular github repository. We'd like to assist you on this issue as efficiently as possible, please have your DMCA paperwork ready so we may better assist you on your problem.

**Comment by hilts-vaughan** [comment]
Hi @DylanDodds,

Thanks for reviewing this case. We are ready to comply once the user(s) provide proper documentation and a list of asset(s) they wish to be removed.

Thanks.

**Comment by Aeirex** [comment]
It doesn't really matter if it is he is the real Justin or not, the PSDs are not owned by you. You do not have the rights to post them regardless. But we will continue to push toward it if it is required.

**Comment by DylanDodds** [comment]
Hi @hilts-vaughan,

Thank you for thanking me for reviewing this case, we're sorry seth is having trouble. Have you tried turning your @Aeirex off and on again?

**Comment by hilts-vaughan** [comment]
@Aeirex,

These PSDs were released to me and the code was licensed under GPL originally. By choosing to push these assets to the repository (which YOU did push, yourself): https://github.com/Pandacoder/blasters/blob/master/BlastersOnline/PuzzleGam/Content/Sprites/Characters/MaleSheet2.png

If you have proof that these assets are to be re(licensed) under an alternative license, please provide it.

**Comment by DylanDodds** [comment]
Hi @Aeirex,
We understand you're having issues, please provide proper documentation to fix these licenses. So we may better assist you.

**Comment by JustinSD** [comment]
The PSD's where at no point licensed or owned by anyone but myself. I can have the artist as well come and comment and provide PayPal screenshots of the payments sent for the artwork. Vaughan Hilts completely backed out of the project after defacing our public website.

 I've contemplated on writing a review to Vaughans company as well. Why would anyone want to have someone working for their company that publicly is stealing someones artwork and claiming they own it. Where is the proof that either of the two of you own this artwork? I see no documents or anything showing that you own what I've paid for. 

Seth @Aeirex  owns every right to any artwork or asset I've paid for on this project. You guys handled the source code which you have every right to share, but at no point were either @hilts-vaughan  or @Pandacoder given rights to share or distribute our assets and UI artwork.

**Comment by Aeirex** [comment]
@hilts-vaughan Yes I did when Justin owned, but that was when the repo was private. The repo was never meant to be public.

I am the proper owner, Justin retired game dev. and gave them to me. If you do not believe he is the real Justin, go ahead and message him on Skype. You guys blocked him, remember? Why would he want you to have the files?

**Comment by JustinSD** [comment]
I'll gladly supply a picture of my ID for anyone claiming this is a false account

**Comment by ndugger** [comment]
Yes, in fact, I think we would all really appreciate both the proof of your identity, and the proof of licensing, and the proof that everything you (Seth) are saying is in fact correct. Baseless claims have no place in the open source world.

**Comment by XerShade** [comment]
Unless either @Aeirex or @JustinSD provides PROOF neither @hilts-vaughan or @Pandacoder need to comply, more so since @Aeirex himself put the files in the repository and he is allegedly the owner of said copyright.

Even then I am sure there are policies in place to prevent people from doing what @Aeirex appears to be doing, and thats issuing a DMCA for something HE HIMSELF committed based on the fact that he does not like or agree with the people he was involved with on this project.

**Comment by JustinSD** [comment]
What a circle jerk, The fact that Axonify hires people that pull this is amusing. Uploading ID now along with a written letter from the original artist and along with PayPal transaction logs. The fact that we have to go through all this on a dead project just so the person who I gave the rights to the artwork can not have them publicly released is a joke.

**Comment by hilts-vaughan** [comment]
No "ID neccessary, @JustinSD just simply forward an e-mail to me with the file(s) you would like removed under an e-mail that would validate your identity and we can have this taken care of quickly.

For the record, I am not even the uploader of this repository here. I'm actually the one trying to help you out here.

Thanks for your cooperation.
